face = @{ "R" | "U" | "F" | "L" | "D" | "B" }
face_small = { "r" | "u" | "f" | "l" | "d" | "b" }

amount = @{ "2" | "'" | "" }
axis_move = ${ face ~ amount }

wide_face = ${ (face ~ "w") | face_small }
depth = { NUMBER? }
wide_move = ${ ((depth ~ wide_face) | face) ~ amount }

// Comments
line_comment = { "//" ~ ANY ~ NEWLINE }
block_comment = { "/*" ~ ANY ~ "*/" }
COMMENT = _{ line_comment | block_comment }

WHITESPACE = _{ " " }
